### ISSUE TITLE
Expired SAS tokens may be cached

### ISSUE THREAD

**Issue by ytechie** [ytechie/eventhubs-js#1]
If your application runs longer than the token expiration and it's allowing this library to generate the SAS token, it will eventually keep an expired token and sending will fail.

**Comment by quy-le** [comment]
https://github.com/quy-le/eventhubs-js

Hi, thanks for doing this. Made some minor changes for my use case. Mainly, keep track of the unix time in the the cached object in order to determine if the token has expired.

**Comment by ytechie** [comment]
Feel free to send me a PR and I'll incorporate your changes!

**Comment by quy-le** [comment]
https://github.com/ytechie/eventhubs-js/pull/3

**Comment by ytechie** [comment]
Thanks!
