### ISSUE TITLE
Add documentation for init method

### ISSUE THREAD

**Issue by andrewjaykeller** [ytechie/eventhubs-js#8]
Cannot seem to figure out or find documentation for `keyName` or `key` required to initialize the `eventHubs`. I [asked Microsoft](https://social.msdn.microsoft.com/Forums/en-US/7b7132f2-2206-4a57-84b4-164e000f6c70/looking-for-way-to-stream-data-into-documentdb-from-nodejs?forum=AzureDocumentDB) about what these are and they could not answer either. 

``` js
eventHubs.init({
    hubNamespace: eventHubsNamespace,
    hubName: eventHubsHubName,
    keyName: eventHubsKeyName,
    key: eventHubsKey
});
```

**Comment by ytechie** [comment]
You can find those in the portal when you provision your event hubs instance. Ideally, you would use the SAS token instead of using the master key.
