### ISSUE TITLE
Add documentation on how to generate a token programatically

### ISSUE THREAD

**Issue by andrewjaykeller** [ytechie/eventhubs-js#9]
As a new user to event hubs, would love some documentation on how to actually generate a SAS token pragmatically in javascript.

**Comment by ytechie** [comment]
couple of options:
1. I added a console write to the code, so if you use the config option with the policy key, it will print one to the screen. This expires pretty quickly, but it will show you a working token. Look at the code to see how this is generated.
2. Take a look at this project: https://github.com/ytechie/event-hubs-sas-generator
